name: zerotier-planet-builder

on:
  workflow_dispatch
        
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Edit the planet IP
      run: sed -i "s/1.1.1.1/${{ secrets.IP }}/g" ./patch/patch.json
    - name: Edit username and password
      run: sed -i "s/admin/${{ secrets.USERNAME }}/g" ./init.sh && sed -i "s/zero-ui/${{ secrets.PASSWORD }}/g" ./init.sh
    - name: Build the Zerotier Planet Docker image
      run: docker build . --file Dockerfile --tag zerotier-planet
    - name: install 7zip
      run: sudo apt-get -qq -y install p7zip-full
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DK_USERNAME }}
          password: ${{ secrets.DK_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: ${{ secrets.DK_USERNAME }}/zerotier-planet:$(date +'%Y-%m-%d_%H-%M') , ${{ secrets.DK_USERNAME }}/zerotier-planet:latest
    - name: Save the Docker image
      run: docker save zerotier-planet|gzip > zerotier-planet.tar.gz && 7z a -t7z -mx=9 -p${{ secrets.PASSWORD }} zerotier-planet.tar.gz.7z zerotier-planet.tar.gz
    - name: Upload the Docker image
      uses: actions/upload-artifact@v4
      with:
          name: zerotier-planet.tar.gz.7z
          path: zerotier-planet.tar.gz.7z
